language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - mkdir -p build/logs
  - php vendor/bin/phpcs --standard=psr2 src/
  - php vendor/bin/phpunit --coverage-clover=./build/logs/coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover ./build/logs/coverage.clover
